### PR TITLE
Minor issues

### PR DESCRIPTION
**Pull request by adius**
Hi,

there were some typos and bugs in your code.
I took the liberty to fix them for you. 😉

Well, actually, [Feram] did it.
It’s a tool that we developed to fix our own code.
If you want to use it as well, it’s really simple to integrate:
[feram.io/help/getting-started]

Hope you like it! 😁

[Feram]: http://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

### CODE REVIEW

**Comment by akaita** [comment]
This feels awful spammy. 

The PR is just changing the indentation of the code with no regards to the style settings of the project.

**Comment by adius** [comment]
Sorry, my fault. Didn't properly check if it aligns with your project. Normally it automatically recognizes the project style, but sometimes it has it's own head 😅

**Comment by adius** [comment]
On the other hand, most xml uses 2 spaces:

image

Maybe you should join the party ;-)

**Comment by akaita** [comment]
> Maybe you should join the party ;-)

You should improve your stats to include filtering by type of project, used framework, ...

**Comment by adius** [comment]
Fair enough. The chart is from here: https://ukupat.github.io/tabs-or-spaces

**Pull request closed without merging**
